[package]
name = "consecutive-vecmap"
version = "0.1.0"
authors = ["Ty Overby <ty@pre-alpha.com>"]
description = "like VecMap, but the keys just need to be clustered together, not necessarily close to 0."
license = "MIT"

[dev-dependencies]
rand = "*"
